project:
  type: book

book:
  title: "R4DS Solutions"
  author: "Jabir"
  date: now
  chapters:
    - index.qmd
    - chapter-2.qmd
    - chapter-3.qmd
    - chapter-4.qmd
    - chapter-6.qmd
    - chapter-7.qmd
    - chapter-8.qmd
    - chapter-9.qmd
    - chapter-11.qmd
    - chapter-12.qmd



format:
  html:
    theme: cosmo

execute:
 freeze: auto